common/models/Game.php
<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\behaviors\SluggableBehavior;
use yii\helpers\ArrayHelper;
use yiidreamteam\upload\ImageUploadBehavior;
use yii\data\ActiveDataProvider;

class Game extends \yii\db\ActiveRecord {

    const STATUS_DELETED = 0;
    const STATUS_ACTIVE = 1;

    public static function tableName() {
        return 'game';
    }

    public function behaviors() {
        return [
            TimestampBehavior::className(),
            [
                'class' => SluggableBehavior::className(),
                'attribute' => 'title',
                'slugAttribute' => 'slug',
            ],
            [
                'class' => ImageUploadBehavior::className(),
                'attribute' => 'image',
                'thumbs' => [
                    'thumb' => ['width' => 350, 'height' => 200],
                ],
                'filePath' => '@webroot/upload/game/[[pk]].[[extension]]',
                'fileUrl' => '/upload/game/[[pk]].[[extension]]',
                'thumbPath' => '@webroot/upload/game/[[profile]]_[[pk]].[[extension]]',
                'thumbUrl' => '/upload/game/[[profile]]_[[pk]].[[extension]]',
            ],
        ];
    }

    public function beforeSave($insert) {
        if (parent::beforeSave($insert)) {
            $this->user_id = Yii::$app->loggedin->user->id;
            return true;
        }
        return false;
    }

    public function rules() {
        return [
            [['title', 'description'], 'required'],
            [['user_id', 'category_id'], 'integer'],
            [['title', 'created_at', 'updated_at', 'image'], 'safe'],
            [['slug'], 'string', 'max' => 255],
            [['slug'], 'unique'],
            ['image', 'file', 'extensions' => 'jpeg, jpg'],
        ];
    }

    public function attributeLabels() {
        return [
            'id' => Yii::t('app', 'ID'),
            'title' => Yii::t('app', 'Title'),
            'slug' => Yii::t('app', 'Slug'),
            'description' => Yii::t('app', 'Description'),
            'created' => Yii::t('app', 'Created'),
            'image' => Yii::t('app', 'Image'),
            'user_id' => Yii::t('app', 'User'),
            'category_id' => Yii::t('app', 'Category'),
            'category.name' => Yii::t('app', 'Category'),
            'created_at' => Yii::t('app', 'Created Date'),
            'updated_at' => Yii::t('app', 'Updated Date'),
        ];
    }

    public function getCategory() {
        return $this->hasOne(GameCategory::className(), ['id' => 'category_id']);
    }

    public function getUser() {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    public function getGameComments() {
        return $this->hasMany(GameComment::className(), ['game_id' => 'id']);
    }

    public function getGameCommentActive() {
        return $this->hasMany(GameComment::className(), ['game_id' => 'id'])->where('status=1');
    }

    public static function find() {
        return new GameQuery(get_called_class());
    }

    public function getCategoryList() {
        $model = GameCategory::find()->all();
        return ArrayHelper::map($model, 'id', 'name');
    }

    public function getDescShort() {
        return substr(strip_tags($this->description), 0, 300) . '...';
    }

    public function getLinkDetail() {
        return Yii::$app->urlManager->createUrl(['game/view', 'slug' => $this->slug]);
    }

    public function getLinkDetailFrontend() {
        return Yii::$app->urlManagerFrontEnd->createUrl(['game/view', 'slug' => $this->slug]);
    }

    public function getTotalComments() {
        return count($this->gameCommentActive);
    }

    public function getCommentDataProvider() {
        $model = GameComment::find()->gameId($this->id)->active();
        return new ActiveDataProvider([
            'query' => $model,
            'pagination' => [
                'pageSize' => 15,
            ],
            'sort' => [
                'defaultOrder' => [
                    'created_at' => SORT_DESC
                ]
            ],
        ]);
    }

}

common/models/GameCommentQuery.php
<?php

namespace common\models;

class GameCommentQuery extends \yii\db\ActiveQuery {

    public function gameId($id) {
        $this->andWhere(['game_id' => $id]);
        return $this;
    }

    public function active() {
        $this->andWhere('[[status]]=1');
        return $this;
    }
    
    
    public function getTotalGameComment(){
        return $this->active()->count();
    }
    

}

common/models/GameQuery.php
<?php

namespace common\models;

use Yii;
use yii\web\NotFoundHttpException;

class GameQuery extends \yii\db\ActiveQuery {
    
    public function bySlug($slug){
        $model = $this->andWhere(['slug'=>$slug])->one();
        if ($model) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function me() {
        $this->andWhere(['user_id' => Yii::$app->loggedin->user->id]);
        return $this;
    }

    public function active() {
        $this->andWhere(['status' => Game::STATUS_ACTIVE]);
        return $this;
    }

    public function search($search) {
        $this->andWhere('title like :search', [':search' => "%" . $search . "%"]);
        return $this;
    }

    public function filterByCategory($category) {
        if ($category > 0)
            $this->andWhere(['category_id' => $category]);
        return $this;
    }
    
    public function getLatest10(){
        return $this->active()->orderBy('id desc')->limit(10)->all();
    }
    
    public function getTotalGame(){
        return $this->active()->count();
    }

}

common/models/UserQuery.php
<?php

namespace common\models;

use Yii;
use yii\db\ActiveQuery;

class UserQuery extends ActiveQuery {

    public function getMyAccount() {
        $this->andWhere('id=:user_id', [':user_id' => Yii::$app->loggedin->user->id]);
        return $this;
    }

    public function administrator() {
        $this->andWhere('group_id=:id', [':id' => User::ADMINISTRATOR]);
        return $this;
    }

    public function findUsernameActive() {
        $this->andWhere('username=:username and status=:status', [':username' => $username, ':status' => User::STATUS_ACTIVE]);
        return $this;
    }

    public function member() {
        $this->where('group_id=:id', [':id' => User::MEMBER]);
        return $this;
    }

    public function active() {
        $this->andWhere(['status' => Game::STATUS_ACTIVE]);
        return $this;
    }
    
    public function getLatest10Members(){
        return $this->member()->active()->orderBy('id desc')->limit(10)->all();
    }
    
    public function getTotalMember(){
        return $this->member()->active()->count();
    }
}

backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use common\models\LoginForm;
use yii\filters\VerbFilter;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionLogin()
    {
        $this->layout = 'login';
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\data\ActiveDataProvider;
use common\models\Game;
use common\models\GameSearch;

class SiteController extends FrontendController {

    public function actionIndex($category = null, $search = null) {
        $model = Game::find();
        if (isset($search))
            $model->search($search);
        if (isset($category))
            $model->filterByCategory($category);
        $dataProvider = new ActiveDataProvider([
            'query' => $model,
            'pagination' => [
                'pageSize' => 15,
            ],
            'sort' => [
                'defaultOrder' => [
                    'created_at' => SORT_DESC,
                    'title' => SORT_ASC,
                ]
            ],
        ]);
        return $this->render('/game/list', ['dataProvider' => $dataProvider, 'search' => $search, 'category' => $category]);
    }

    public function actionLogin() {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                        'model' => $model,
            ]);
        }
    }

    public function actionLogout() {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact() {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending email.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                        'model' => $model,
            ]);
        }
    }

    public function actionAbout() {
        return $this->render('about');
    }

    public function actionSignup() {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
                    'model' => $model,
        ]);
    }

    public function actionRequestPasswordReset() {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->getSession()->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->getSession()->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
                    'model' => $model,
        ]);
    }

    public function actionResetPassword($token) {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->getSession()->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
                    'model' => $model,
        ]);
    }

}

backend/views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

backend/views/site/index.php
<?php

use common\models\User;
use common\models\Game;
use common\models\GameComment;
use common\models\GameCategory;

$this->title = 'Dashboard';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-aqua">
            <div class="inner">
                <h3><?= User::find()->totalMember ?></h3>
                <p>Members</p>
            </div>
        </div>
    </div><!-- ./col -->
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-green">
            <div class="inner">
                <h3><?= Game::find()->totalGame ?></h3>
                <p>Posts</p>
            </div>
        </div>
    </div><!-- ./col -->
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-yellow">
            <div class="inner">
                <h3><?= GameComment::find()->totalGameComment ?></h3>
                <p>Comments</p>
            </div>
        </div>
    </div><!-- ./col -->
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-red">
            <div class="inner">
                <h3><?= GameCategory::find()->totalGameCategory ?></h3>
                <p>Categories</p>
            </div>
        </div>
    </div><!-- ./col -->
</div>
<div class="row">
    <!-- Left col -->
    <div class="col-md-6">
        <!-- TABLE: LATEST ORDERS -->
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">Latest Members</h3>
                <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                </div>
            </div><!-- /.box-header -->
            <div class="box-body">
                <div class="table-responsive">
                    <table class="table no-margin">
                        <thead>
                            <tr>
                                <th><?= Yii::t('app', 'Join Date') ?></th>
                                <th><?= Yii::t('app', 'Username') ?></th>
                                <th><?= Yii::t('app', 'Fullname') ?></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach (User::find()->latest10Members as $row): ?>
                                <tr>
                                    <td><?= Yii::$app->formatter->asDatetime($row->created_at) ?></td>
                                    <td><?= $row->username ?></td>
                                    <td><?= $row->fullname ?></td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div><!-- /.table-responsive -->
            </div><!-- /.box-body -->
        </div><!-- /.box -->
    </div><!-- /.col -->

    <div class="col-md-6">
        <!-- PRODUCT LIST -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Recently Added Posts</h3>
                <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                </div>
            </div><!-- /.box-header -->
            <div class="box-body">
                <ul class="products-list product-list-in-box">
                    <?php foreach (Game::find()->latest10 as $row): ?>
                        <li class="item">
                            <div class="product-info">
                                <a href="<?= $row->linkDetailFrontend ?>" class="product-title"><?= $row->title ?></a>
                                <span class="product-description">
                                    <?= $row->descShort ?>
                                </span>
                            </div>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div><!-- /.box-body -->
        </div><!-- /.box -->
    </div><!-- /.col -->
</div>

backend/views/site/login.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
?>
<div class="login-box">
    <div class="login-logo">
        <a href="../../index2.html"><b>Admin</b>Game Portal</a>
    </div><!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg">Sign in to start your session</p>
        <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>
        <?= $form->field($model, 'username') ?>
        <?= $form->field($model, 'password')->passwordInput() ?>
        <?= $form->field($model, 'rememberMe')->checkbox() ?>
        <div class="row">
            <div class="col-xs-8">
            </div><!-- /.col -->
            <div class="col-xs-4">
                <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
            </div><!-- /.col -->
        </div>
        <?php ActiveForm::end(); ?>
    </div><!-- /.login-box-body -->
</div><!-- /.login-box -->