backend/controllers/GameController.php
<?php

namespace backend\controllers;

use Yii;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\helpers\Json;
use common\models\Game;
use common\models\GameComment;

class GameController extends BackendController {

    public function actionIndex() {
        $model = Game::find()->active()->orderBy('created_at desc');
        return $this->render('index', [
                    'model' => $model,
        ]);
    }

    public function actionUpdate($id) {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post())) {
            if ($model->save())
                return $this->redirect(['index']);
        }
        return $this->render('form', [
                    'model' => $model,
        ]);
    }

    public function actionView($slug) {
        $model = Game::find()->bySlug($slug);
        $comment = new GameComment();
        if ($comment->load(Yii::$app->request->post())) {
            $comment->game_id = $model->id;
            if($comment->save()){
                $comment->comment = "";
                Yii::$app->getSession()->setFlash('success', 'Your comment has been added');
            }
        }
        return $this->render('view', [
                    'model' => $model,
                    'comment' => $comment
        ]);
    }

    public function actionDelete($id) {
        $model = $this->findModel($id);
        $model->status = Game::STATUS_DELETED;
        if ($model->save())
            return $this->redirect(['index']);
    }

    protected function findModel($id) {
        if (($model = Game::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

frontend/controllers/GameController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\helpers\Json;
use common\models\Game;
use common\models\GameComment;

class GameController extends FrontendController {

    public function actionIndex() {
        $model = Game::find()->me()->active()->orderBy('created_at desc');
        return $this->render('index', [
                    'model' => $model,
        ]);
    }

    public function actionPost() {
        $model = new Game();
        if ($model->load(Yii::$app->request->post())) {
            if ($model->save()) {
                return $this->redirect(['index']);
            }
        }
        return $this->render('form', array(
                    'model' => $model,
        ));
    }

    public function actionUpdate($id) {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post())) {
            $model->image = UploadedFile::getInstance($model, 'image');
            if ($model->save())
                return $this->redirect(['index']);
        }
        return $this->render('form', [
                    'model' => $model,
        ]);
    }

    public function actionView($slug) {
        $model = Game::find()->bySlug($slug);
        $comment = new GameComment();
        if ($comment->load(Yii::$app->request->post())) {
            $comment->game_id = $model->id;
            if($comment->save()){
                $comment->comment = "";
                Yii::$app->getSession()->setFlash('success', 'Your comment has been added');
            }
        }
        return $this->render('view', [
                    'model' => $model,
                    'comment' => $comment
        ]);
    }

    public function actionDelete($id) {
        $model = $this->findModel($id);
        $model->status = Game::STATUS_DELETED;
        if ($model->save())
            return $this->redirect(['index']);
    }

    protected function findModel($id) {
        if (($model = Game::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

frontend/views/layouts/main.php
<?php

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use frontend\widgets\Alert;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <body>
        <?php $this->beginBody() ?>
        <div class="wrap">
            <?php
            NavBar::begin([
                'brandLabel' => Yii::t('app', 'Online Game Portal'),
                'brandUrl' => Yii::$app->homeUrl,
                'options' => [
                    'class' => 'navbar-inverse navbar-fixed-top bg-navy color-palette',
                ],
            ]);
            $menuItems = [
                ['label' => Yii::t('app', 'Home'), 'url' => ['/site/index']],
            ];
            if (Yii::$app->user->isGuest) {
                $menuItems[] = ['label' => Yii::t('app', 'Signup'), 'url' => ['/site/signup']];
                $menuItems[] = ['label' => Yii::t('app', 'Login'), 'url' => ['/site/login']];
            } else {
                $menuItems[] = ['label' => Yii::t('app', 'Post'), 'items' => [
                        ['label' => Yii::t('app', 'New Post'), 'url' => ['/game/post']],
                        ['label' => Yii::t('app', 'My Posts'), 'url' => ['/game/index']]
                ]];
                $menuItems[] = ['label' => Yii::t('app', 'My Account'), 'items' => [
                        ['label' => Yii::t('app', 'Update Profile'), 'url' => ['/account/update']],
                        ['label' => Yii::t('app', 'Change Password'), 'url' => ['/account/changepassword']]
                ]];
                $menuItems[] = ['label' => Yii::t('app', 'Language'), 'items' => [
                        ['label' => Yii::t('app', 'Indonesia'), 'url' => ['?lang=id']],
                        ['label' => Yii::t('app', 'English'), 'url' => ['?lang=en_US']]
                ]];
                $menuItems[] = [
                    'label' => Yii::t('app', 'Logout').'(' . Yii::$app->user->identity->username . ')',
                    'url' => ['/site/logout'],
                    'linkOptions' => ['data-method' => 'post']
                ];
            }
            echo Nav::widget([
                'options' => ['class' => 'navbar-nav navbar-right'],
                'items' => $menuItems,
            ]);
            NavBar::end();
            ?>

            <div class="container">
                <?=
                Breadcrumbs::widget([
                    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                ])
                ?>
                <?= Alert::widget() ?>
                <?= $content ?>
            </div>
        </div>

        <footer class="footer">
            <div class="container">
                <p class="pull-left">&copy; Buhori Dermawan <?= date('Y') ?></p>
            </div>
        </footer>

        <?php $this->endBody() ?>
    </body>
</html>
<?php $this->endPage() ?>