common/models/Game.php
<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\behaviors\SluggableBehavior;
use yii\helpers\ArrayHelper;
use yiidreamteam\upload\ImageUploadBehavior;
use yii\data\ActiveDataProvider;

class Game extends \yii\db\ActiveRecord {

    const STATUS_DELETED = 0;
    const STATUS_ACTIVE = 1;

    public static function tableName() {
        return 'game';
    }

    public function behaviors() {
        return [
            TimestampBehavior::className(),
            [
                'class' => SluggableBehavior::className(),
                'attribute' => 'title',
                'slugAttribute' => 'slug',
            ],
            [
                'class' => ImageUploadBehavior::className(),
                'attribute' => 'image',
                'thumbs' => [
                    'thumb' => ['width' => 350, 'height' => 200],
                ],
                'filePath' => '@webroot/upload/game/[[pk]].[[extension]]',
                'fileUrl' => '/upload/game/[[pk]].[[extension]]',
                'thumbPath' => '@webroot/upload/game/[[profile]]_[[pk]].[[extension]]',
                'thumbUrl' => '/upload/game/[[profile]]_[[pk]].[[extension]]',
            ],
        ];
    }

    public function beforeSave($insert) {
        if (parent::beforeSave($insert)) {
            $this->user_id = Yii::$app->loggedin->user->id;
            return true;
        }
        return false;
    }

    public function rules() {
        return [
            [['title', 'description'], 'required'],
            [['user_id', 'category_id'], 'integer'],
            [['title', 'created_at', 'updated_at', 'image'], 'safe'],
            [['slug'], 'string', 'max' => 255],
            [['slug'], 'unique'],
            ['image', 'file', 'extensions' => 'jpeg, jpg'],
        ];
    }

    public function attributeLabels() {
        return [
            'id' => Yii::t('app', 'ID'),
            'title' => Yii::t('app', 'Title'),
            'slug' => Yii::t('app', 'Slug'),
            'description' => Yii::t('app', 'Description'),
            'created' => Yii::t('app', 'Created'),
            'image' => Yii::t('app', 'Image'),
            'user_id' => Yii::t('app', 'User'),
            'category_id' => Yii::t('app', 'Category'),
            'category.name' => Yii::t('app', 'Category'),
            'created_at' => Yii::t('app', 'Created Date'),
            'updated_at' => Yii::t('app', 'Updated Date'),
        ];
    }

    public function getCategory() {
        return $this->hasOne(GameCategory::className(), ['id' => 'category_id']);
    }

    public function getUser() {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    public function getGameComments() {
        return $this->hasMany(GameComment::className(), ['game_id' => 'id']);
    }

    public function getGameCommentActive() {
        return $this->hasMany(GameComment::className(), ['game_id' => 'id'])->where('status=1');
    }

    public static function find() {
        return new GameQuery(get_called_class());
    }

    public function getCategoryList() {
        $model = GameCategory::find()->all();
        return ArrayHelper::map($model, 'id', 'name');
    }

    public function getDescShort() {
        return substr(strip_tags($this->description), 0, 300) . '...';
    }

    public function getLinkDetail() {
        return Yii::$app->urlManager->createUrl(['game/view', 'slug' => $this->slug]);
    }

    public function getLinkDetailFrontend() {
        return Yii::$app->urlManagerFrontEnd->createUrl(['game/view', 'slug' => $this->slug]);
    }

    public function getTotalComments() {
        return count($this->gameCommentActive);
    }

    public function getCommentDataProvider() {
        $model = GameComment::find()->gameId($this->id)->active();
        return new ActiveDataProvider([
            'query' => $model,
            'pagination' => [
                'pageSize' => 15,
            ],
            'sort' => [
                'defaultOrder' => [
                    'created_at' => SORT_DESC
                ]
            ],
        ]);
    }

}

backend/controllers/GameController.php
<?php

namespace backend\controllers;

use Yii;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\helpers\Json;
use common\models\Game;
use common\models\GameComment;

class GameController extends BackendController {

    public function actionIndex() {
        $model = Game::find()->active()->orderBy('created_at desc');
        return $this->render('index', [
                    'model' => $model,
        ]);
    }

    public function actionUpdate($id) {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post())) {
            if ($model->save())
                return $this->redirect(['index']);
        }
        return $this->render('form', [
                    'model' => $model,
        ]);
    }

    public function actionView($slug) {
        $model = Game::find()->bySlug($slug);
        $comment = new GameComment();
        if ($comment->load(Yii::$app->request->post())) {
            $comment->game_id = $model->id;
            if($comment->save()){
                $comment->comment = "";
                Yii::$app->getSession()->setFlash('success', 'Your comment has been added');
            }
        }
        return $this->render('view', [
                    'model' => $model,
                    'comment' => $comment
        ]);
    }

    public function actionDelete($id) {
        $model = $this->findModel($id);
        $model->status = Game::STATUS_DELETED;
        if ($model->save())
            return $this->redirect(['index']);
    }

    protected function findModel($id) {
        if (($model = Game::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

frontend/controllers/GameController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\helpers\Json;
use common\models\Game;
use common\models\GameComment;

class GameController extends FrontendController {

    public function actionIndex() {
        $model = Game::find()->me()->active()->orderBy('created_at desc');
        return $this->render('index', [
                    'model' => $model,
        ]);
    }

    public function actionPost() {
        $model = new Game();
        if ($model->load(Yii::$app->request->post())) {
            if ($model->save()) {
                return $this->redirect(['index']);
            }
        }
        return $this->render('form', array(
                    'model' => $model,
        ));
    }

    public function actionUpdate($id) {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post())) {
            $model->image = UploadedFile::getInstance($model, 'image');
            if ($model->save())
                return $this->redirect(['index']);
        }
        return $this->render('form', [
                    'model' => $model,
        ]);
    }

    public function actionView($slug) {
        $model = Game::find()->bySlug($slug);
        $comment = new GameComment();
        if ($comment->load(Yii::$app->request->post())) {
            $comment->game_id = $model->id;
            if($comment->save()){
                $comment->comment = "";
                Yii::$app->getSession()->setFlash('success', 'Your comment has been added');
            }
        }
        return $this->render('view', [
                    'model' => $model,
                    'comment' => $comment
        ]);
    }

    public function actionDelete($id) {
        $model = $this->findModel($id);
        $model->status = Game::STATUS_DELETED;
        if ($model->save())
            return $this->redirect(['index']);
    }

    protected function findModel($id) {
        if (($model = Game::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

frontend/views/game/_comment.php
<?php

use common\components\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\ListView;
use yii\data\ActiveDataProvider;
?>
<?php
$form = ActiveForm::begin([
            'options' => [
                'class' => 'form-horizontal'
            ],
            'fieldConfig' => [
                'template' => "{label}\n<div class=\"col-lg-6\">{input}\n<div>{error}</div></div>",
                'labelOptions' => ['class' => 'col-lg-1 control-label'],
            ],
        ]);
?>
<div class="row">
    <div class="col-sm-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title"><?= Yii::t('app', 'Comment') ?></h3>
            </div>
            <?php if (!Yii::$app->user->isGuest): ?>
                <div class="box-body">
                    <?= $form->field($comment, 'comment')->textarea() ?>
                </div>
                <div class="box-footer">
                    <div class="row">
                        <div class="col-sm-6 col-sm-offset-1">
                            <div class="btn-toolbar">
                                <button class="btn-primary btn"><i class="fa fa-check"></i> Post</button>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
            <div class="box-body">
                <?php
                echo ListView::widget([
                    'dataProvider' => $model->commentDataProvider,
                    'itemView' => '_comment_list',
                    'emptyText' => 'No comments found.'
                ]);
                ?>
            </div>
        </div>

    </div>
</div>
<?php ActiveForm::end(); ?>

frontend/views/game/_comment_list.php
<div class="row item-comment">
    <div class="col-lg-12">
        <div>
        <small>- <?= Yii::$app->formatter->asDatetime($model->created_at) ?> <cite title="<?= $model->user->username ?>"><?= $model->user->fullname ?></cite></small>
        </div>
        <?= $model->comment ?>
    </div>
</div>

frontend/views/game/_list.php
<div class="col-md-4 portfolio-item">
    <a href="<?= $model->linkDetail ?>">
        <img class="img-responsive" src="<?= $model->getThumbFileUrl('image', 'thumb', '/upload/game/default.jpg') ?>" alt="">
    </a>
    <h3 class="box-title">
        <a href="<?= $model->linkDetail ?>"><?= $model->title ?></a>
    </h3>
    <div>
        <small>- <?= Yii::$app->formatter->asDatetime($model->created_at) ?> <cite title="<?= $model->user->username ?>"><?= $model->user->fullname ?></cite></small>
        <span class="pull-right">Comments(<?= $model->totalComments ?>)</span>
    </div>
    <p><?= $model->descShort ?></p>
</div>

frontend/views/game/form.php
<?php

use common\components\helpers\Html;
use yii\widgets\ActiveForm;
use dosamigos\tinymce\TinyMce;

$this->title = ($model->isNewRecord ? Yii::t('app', 'Create New Game') : Yii::t('app', 'Update Game'));
?>
<?php
$form = ActiveForm::begin([
            'options' => ['enctype' => 'multipart/form-data', 'class' => 'form-horizontal'],
            'fieldConfig' => [
                'template' => "{label}\n<div class=\"col-lg-6\">{input}\n<div>{error}</div></div>",
                'labelOptions' => ['class' => 'col-lg-3 control-label'],
            ],
        ]);
?>
<div class="row">
    <div class="col-sm-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title"><?= $this->title ?></h3>
            </div>
            <div class="box-body">
                <?= $form->field($model, 'title') ?>
                <?= $form->field($model, 'category_id')->dropDownList($model->categoryList) ?>
                <?=
                $form->field($model, 'description')->widget(TinyMce::className(), [
                    'options' => ['rows' => 6],
                    'language' => 'en_CA',
                    'clientOptions' => [
                        'plugins' => [
                            "advlist autolink lists link charmap print preview anchor",
                            "searchreplace visualblocks code fullscreen",
                            "insertdatetime media table contextmenu paste"
                        ],
                        'toolbar' => "undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
                    ]
                ]);
                ?>
                <div class="form-group">
                    <div class="row">
                        <div class="col-lg-3"></div>
                        <div class="col-lg-4">
                            <!-- Thumb 1 (thumb profile) -->
                            <?= Html::img($model->getThumbFileUrl('image', 'thumb', '/upload/game/default.jpg'), ['class' => 'img-thumbnail']) ?>
                        </div>
                    </div>
                </div>
                <?= $form->field($model, 'image')->fileInput(['accept' => 'image/*']) ?>
            </div>
            <div class="box-footer">
                <div class="row">
                    <div class="col-sm-6 col-sm-offset-3">
                        <div class="btn-toolbar">
                            <button class="btn-primary btn"><i class="fa fa-check"></i> Post</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
<?php ActiveForm::end(); ?>

frontend/views/game/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\data\ActiveDataProvider;

$this->title = Yii::t('app', 'Games');
?>
<div class="row">
    <div class="col-md-12"><p class="pull-left"><?= Html::a('<i class="fa fa-plus"></i> <span>' . Yii::t('app', 'New ' . $this->title) . '</span>', ['post'], ['class' => 'btn btn-default DTTT_button_text']) ?></p>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="box box-primary">
            <div class="box-body">
                <?=
                GridView::widget([
                    'dataProvider' => new ActiveDataProvider([
                        'query' => $model,
                            ]),
                    'columns' => [
                        'created_at:datetime',
                        'updated_at:datetime',
                        'category.name',
                        'title',
                        [
                            'class' => 'yii\grid\ActionColumn',
                            'template' => '<span class="pull-right">{view} {update} {delete}</span>',
                            'buttons' => [
                                'view' => function ($url, $model, $key) {
                            return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', $model->linkDetail, array_merge([
                                        'title' => Yii::t('yii', 'Beacons'),
                                        'data-pjax' => '0',
                            ]));
                        }]
                        ]
                    ],
                    'tableOptions' => ['class' => 'table table-striped']
                ]);
                ?>
            </div>
        </div>
    </div>
</div>

frontend/views/game/list.php
<?php

use yii\widgets\ListView;
use common\components\helpers\Html;
use yii\widgets\ActiveForm;
use common\models\GameCategory;

/* @var $this yii\web\View */
$this->title = Yii::t('app', 'Online Game Portal');
?>

<!-- Page Header -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><?= $this->title ?>
        </h1>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <?php $form = ActiveForm::begin(['method' => 'GET', 'action' => '/']); ?>
        <div class="col-lg-2">
            <?= Html::dropDownList('category', $category, GameCategory::find()->listForSearch(), ['class' => 'form-control']) ?>
        </div>
        <div class="col-lg-9">
            <?= Html::input('text', 'search', $search, ['class' => 'form-control','placeholder'=>Yii::t('app', 'Find Title')]) ?>
        </div>
        <div class="col-lg-1">
            <button class="btn-primary btn searchButton"><i class="fa fa-search"></i> <?= Yii::t('app', 'Search'); ?></button>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>
<!-- /.row -->

<?php
echo ListView::widget([
    'dataProvider' => $dataProvider,
    'itemView' => '_list',
]);
?>

frontend/views/game/view.php
<?php

use yii\helpers\Html;

$this->title = $model->title;
?>
<section class="content-header">
    <h1>
        <?= $this->title ?>
        <small><?= $model->category->name ?></small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?= Yii::$app->getHomeUrl() ?>">Home</a></li>
        <li><a href="#"><?= $model->category->name ?></a></li>
        <li class="active"><?= $this->title ?></li>
    </ol>
</section>
<section class="content">
    <div class="box">
            <?php if ($model->getImageFileUrl('image', 'empty') != 'empty'): ?>
                <div class="box-header with-border">
                    <?= Html::img($model->getImageFileUrl('image', '/upload/game/default.png')) ?>
                </div>
            <?php endif; ?>
            <div class="box-body">
                <?= $model->description ?>
            </div>
        <div class="box-body">
            <?php echo Yii::$app->controller->renderPartial('_comment', ['model' => $model, 'comment' => $comment]) ?>
        </div>
    </div>
</section>